# Generated by Django 3.1.2 on 2024-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20240908_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='Теги', through='articles.Scopes', to='articles.Article'),
        ),
    ]
